### ISSUE TITLE
[Feature] The CDC Action parameter supports yaml file

### ISSUE THREAD

**Issue by melin** [apache/paimon#3194]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

CDC Action requires a large number of parameters, which is difficult to reuse and maintain. Recommended reference flink cdc yaml。IE:

```yaml
source:
     type: mysql
     name: MySQL Source
     hostname: 127.0.0.1
     port: 3306
     username: admin
     password: pass
     tables: adb.\.*
     server-id: 5401-5404

     metadata_column: xxx
     including_tables: xxx
     excluding_tables: xxxx

sink:
    warehouse: hdfs:///path/to/warehouse
    database: test_db 
    table: test_table 
    partition_keys: xxx
    primary_keys: xxxx
    ignore_incompatible: false
    merge_shards: xx
    table_prefix: xxx
    table_suffix: xxx

catalog:
   metastore: hive
   uri: thrift://hive-metastore:9083
 
pipeline:
    bucket: 4
    changelog-producer: input
    sink.parallelism: 4
    type_mapping: xxxx
    computed_column: xxxx
    mode: divided
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!
